version: '3.8'
services:
  mysql-master:
    container_name: mysql-master 
    image: mysql:5.7.31
    restart: always
    ports:
      - 13306:3306 
    privileged: true
    volumes:
      # 这个只对mysql主从进行验证 没有持久化配置以及日志相关的映射
      # - $PWD/master/conf/my.cnf:/etc/mysql/my.cnf
      - ./script/mysql_master/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    command: [
        '--server-id=1',
        '--log-bin=mysql-bin',
        #'--binlog-ignore-db=mysql',
        #'--sync_binlog = 1',
        #'--slave-skip-errors = all',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      - myweb
      
  mysql-slave:
    container_name: mysql-slave 
    image: mysql:5.7.31
    restart: always
    ports:
      - 23306:3306 
    privileged: true
    volumes:
      # 这个只对mysql主从进行验证 没有持久化配置以及日志相关的映射
      # - $PWD/slave/conf/my.cnf:/etc/mysql/my.cnf
      - ./script/mysql_slave/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    command: [
        '--server-id=2',
        '--log-bin=mysql-bin',
        #'--binlog-ignore-db=mysql',
        #'--slave-skip-errors = all',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
    ]
    networks:
      - myweb    
  
  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - myweb

  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
#      - 允许自动创建 topic，线上不要开启
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - myweb

networks:
  myweb:
    driver: bridge